### ISSUE TITLE
package.json incorrect module entry

### ISSUE THREAD

**Issue by trynulI** [JacobWeisenburger/zod_utilz#10]
_...package "zod_utilz". The package may have incorrect main/module/exports..._

there is a problem when using it in vitejs, it reports that the 'module entry' is incorrect
is **index.ts** instead of **index.js**

![image](https://github.com/JacobWeisenburger/zod_utilz/assets/56323304/16647da4-37fa-489f-9cd1-963acce404a1)
![image](https://github.com/JacobWeisenburger/zod_utilz/assets/56323304/b6259f53-3949-4d4d-9366-694836214e3e)

**Comment by issam-seghir** [comment]
"I am facing the same issues . Have you found any workaround?"

**Comment by JacobWeisenburger** [comment]
I'm working on a fix

**Comment by JacobWeisenburger** [comment]
Should be working now: [0.8.2](https://github.com/JacobWeisenburger/zod_utilz/releases/tag/0.8.2)

Please let me know if it's working for you.

**Comment by sneko** [comment]
@JacobWeisenburger I think it should be reopen. I'm using `0.8.3` but facing this warning every time I run my program:
```
(node:44267) [DEP0151] DeprecationWarning: No "main" or "exports" field defined in the package.json for /xxxxxxxxxxxx/node_modules/zod_utilz/ resolving the main entry point "index.js", imported from /xxxxxxxxxxxx/src/models/entities/product.ts.
Default "index" lookups for the main are deprecated for ES modules.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:44267) [DEP0151] DeprecationWarning: No "main" or "exports" field defined in the package.json for /xxxxxxxxxxxx/node_modules/zod_utilz/ resolving the main entry point "index.js", imported from /xxxxxxxxxxxx/src/models/entities/parsers/prestashop.ts.
Default "index" lookups for the main are deprecated for ES modules.
```

**Comment by JacobWeisenburger** [comment]
please make a new issue for this
