### ISSUE TITLE
z.infer should be z.input

### ISSUE THREAD

**Issue by scamden** [JacobWeisenburger/zod_utilz#13]
https://github.com/JacobWeisenburger/zod_utilz/blob/2615a26eececeea1134ef53a581e00fb363bf3a4/src/useTypedParsers.ts#L28

if i pass   
```ts
z
.number()
.int()
.min(1)
.default(DEFAULT_CONCURRENCY)
```

to `useTypedParsers` right now the resulting .parse won't accept `undefined` but I believe it should!

using `z.input<Schema>` solves this for me, just thought I'd open this as a possible improvement. Thanks for this really helpful library!

**Comment by JacobWeisenburger** [comment]
good catch. I'll get that fixed asap

**Comment by JacobWeisenburger** [comment]
Should be fixed in https://github.com/JacobWeisenburger/zod_utilz/releases/tag/0.8.3. Let me know if it works for you?

**Comment by scamden** [comment]
looks great! thanks for the quick turnaround!

**Comment by JacobWeisenburger** [comment]
Thanks for clearly describing your issue. lol. It is crazy how many people struggle with making a simple explanation. :D
